#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/Users/latimerb/opt/anaconda3/lib/python3.7/site-packages/neuron/.data"
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/Users/latimerb/opt/anaconda3/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/latimerb/BLA_SingleCells/GapJunction/x86_64/.libs/libnrnmech.so" "$@"
